server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:127.0.0.1}:${DB_PORT:3306}/${DB_NAME:book_stream}?createDatabaseIfNotExist=true
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: karnan.learningjgjhgjhghg@gmail.com
    password: bydbtrpzluhpzjxrjkgjhgkjh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com

# App Properties
bookStream:
  app:
    jwtSecret: bezKoderSecretKeyhjghhj
    jwtExpirationMs: 3600000
    jwtRefreshExpirationMs: 86400000
