server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/book_stream?createDatabaseIfNotExist=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: karnan.learning@gmail.com
    password: bydbtrpzluhpzjxr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com

# App Properties
bookStream:
  app:
    jwtSecret: bezKoderSecretKey
    jwtExpirationMs: 3600000
    jwtRefreshExpirationMs: 86400000